// Permission constants for RBAC system
// Format: resource:action

export const PERMISSIONS = {
  // Contract permissions
  CONTRACT_CREATE: "contract:create",
  CONTRACT_READ: "contract:read",
  CONTRACT_UPDATE: "contract:update",
  CONTRACT_DELETE: "contract:delete",
  CONTRACT_SUBMIT: "contract:submit",
  CONTRACT_APPROVE: "contract:approve",
  CONTRACT_REJECT: "contract:reject",
  CONTRACT_SEND_SIGNATURE: "contract:send_signature",
  CONTRACT_SEND_TO_CLIENT: "contract:send_to_client",
  CONTRACT_MARK_CLIENT_APPROVED: "contract:mark_client_approved",
  CONTRACT_GENERATE_STAMP_PAPER: "contract:generate_stamp_paper",
  
  // Simplified workflow permissions
  CONTRACT_LEGAL_APPROVE: "contract:legal:approve",
  CONTRACT_ADMIN_APPROVE: "contract:admin:approve",
  CONTRACT_CLIENT_APPROVE: "contract:client:approve",
  CONTRACT_SEND_FOR_SIGNATURE: "contract:send:signature",

  // Invoice permissions
  INVOICE_CREATE: "invoice:create",
  INVOICE_READ: "invoice:read",
  INVOICE_UPDATE: "invoice:update",
  INVOICE_DELETE: "invoice:delete",
  INVOICE_APPROVE: "invoice:approve",
  INVOICE_GENERATE: "invoice:generate",
  INVOICE_SEND: "invoice:send",

  // Payment permissions
  PAYMENT_CREATE: "payment:create",
  PAYMENT_READ: "payment:read",
  PAYMENT_UPDATE: "payment:update",
  PAYMENT_DELETE: "payment:delete",
  PAYMENT_PROCESS: "payment:process",
  PAYMENT_REFUND: "payment:refund",
  PAYMENT_APPROVE: "payment:approve",

  // Draft Payment permissions
  DRAFT_PAYMENT_CREATE: "draft_payment:create",
  DRAFT_PAYMENT_READ: "draft_payment:read",
  DRAFT_PAYMENT_APPROVE: "draft_payment:approve",
  DRAFT_PAYMENT_REJECT: "draft_payment:reject",

  // Late Fee permissions
  LATE_FEE_CREATE: "late_fee:create",
  LATE_FEE_READ: "late_fee:read",
  LATE_FEE_APPLY: "late_fee:apply",
  LATE_FEE_WAIVE: "late_fee:waive",

  // Client permissions
  CLIENT_CREATE: "client:create",
  CLIENT_READ: "client:read",
  CLIENT_UPDATE: "client:update",
  CLIENT_DELETE: "client:delete",
  CLIENT_APPROVE: "client:approve",
  CLIENT_APPROVE_ONBOARDING: "client:approve_onboarding",

  // User permissions
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_ASSIGN_ROLE: "user:assign_role",

  // Role permissions
  ROLE_CREATE: "role:create",
  ROLE_READ: "role:read",
  ROLE_UPDATE: "role:update",
  ROLE_DELETE: "role:delete",

  // Report permissions
  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",

  // Transaction permissions
  TRANSACTION_READ: "transaction:read",
  TRANSACTION_MONITOR: "transaction:monitor",

  // Integration permissions
  INTEGRATION_READ: "integration:read",
  INTEGRATION_UPDATE: "integration:update",
  INTEGRATION_CONFIGURE: "integration:configure",

  // Booking permissions
  BOOKING_CREATE: "booking:create",
  BOOKING_READ: "booking:read",
  BOOKING_UPDATE: "booking:update",
  BOOKING_DELETE: "booking:delete",
  BOOKING_APPROVE: "booking:approve",
  BOOKING_CANCEL: "booking:cancel",

  // Event permissions
  EVENT_CREATE: "event:create",
  EVENT_READ: "event:read",
  EVENT_UPDATE: "event:update",
  EVENT_DELETE: "event:delete",
  EVENT_PUBLISH: "event:publish",

  // Ticket permissions
  TICKET_CREATE: "ticket:create",
  TICKET_READ: "ticket:read",
  TICKET_UPDATE: "ticket:update",
  TICKET_DELETE: "ticket:delete",
  TICKET_ASSIGN: "ticket:assign",
  TICKET_RESOLVE: "ticket:resolve",

  // Member permissions
  MEMBER_CREATE: "member:create",
  MEMBER_READ: "member:read",
  MEMBER_UPDATE: "member:update",
  MEMBER_DELETE: "member:delete",
  MEMBER_ACTIVATE: "member:activate",
  MEMBER_DEACTIVATE: "member:deactivate",
  MEMBER_ASSIGN_WORKSPACE: "member:assign_workspace",
  MEMBER_MANAGE_ACCESS: "member:manage_access",

  // Inventory permissions
  INVENTORY_READ: "inventory:read",
  INVENTORY_UPDATE: "inventory:update",
  INVENTORY_BLOCK: "inventory:block",

  // System permissions
  SYSTEM_ADMIN: "*:*", // Super admin - all permissions
};

// Role definitions with their permissions
export const ROLE_PERMISSIONS = {
  contract_creator: [
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_SUBMIT,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.REPORT_READ,
  ],

  approver: [
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_SUBMIT,
    PERMISSIONS.CONTRACT_APPROVE,
    PERMISSIONS.CONTRACT_REJECT,
    PERMISSIONS.CONTRACT_SEND_SIGNATURE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_APPROVE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.REPORT_READ,
  ],

  billing_admin: [
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_GENERATE,
    PERMISSIONS.INVOICE_SEND,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.PAYMENT_PROCESS,
    PERMISSIONS.LATE_FEE_CREATE,
    PERMISSIONS.LATE_FEE_READ,
    PERMISSIONS.LATE_FEE_APPLY,
    PERMISSIONS.LATE_FEE_WAIVE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],

  operations_admin: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_MONITOR,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],

  system_admin: [
    PERMISSIONS.SYSTEM_ADMIN, // Has all permissions
  ],

  // New roles for updated onboarding flow
  sales: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_SUBMIT,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MEMBER_READ,
  ],

  legal_team: [
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_SUBMIT,
    PERMISSIONS.CONTRACT_LEGAL_APPROVE,
    PERMISSIONS.CONTRACT_SEND_TO_CLIENT,
    PERMISSIONS.CONTRACT_MARK_CLIENT_APPROVED,
    PERMISSIONS.CONTRACT_GENERATE_STAMP_PAPER,
    PERMISSIONS.CONTRACT_SEND_SIGNATURE,
    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
  ],

  senior_management: [
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_APPROVE,
    PERMISSIONS.CONTRACT_REJECT,
    PERMISSIONS.CONTRACT_ADMIN_APPROVE,
    PERMISSIONS.CONTRACT_SEND_FOR_SIGNATURE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CLIENT_APPROVE,
    PERMISSIONS.CLIENT_APPROVE_ONBOARDING,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_APPROVE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.LATE_FEE_WAIVE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_MONITOR,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_ASSIGN_ROLE,
    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.INTEGRATION_UPDATE,
  ],

  finance_senior: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CLIENT_APPROVE,
    PERMISSIONS.CLIENT_APPROVE_ONBOARDING,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_APPROVE,
    PERMISSIONS.CONTRACT_REJECT,
    PERMISSIONS.CONTRACT_SUBMIT,
    PERMISSIONS.CONTRACT_SEND_SIGNATURE,
    PERMISSIONS.CONTRACT_SEND_TO_CLIENT,
    PERMISSIONS.CONTRACT_MARK_CLIENT_APPROVED,
    PERMISSIONS.CONTRACT_GENERATE_STAMP_PAPER,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE,
    PERMISSIONS.INVOICE_APPROVE,
    PERMISSIONS.INVOICE_GENERATE,
    PERMISSIONS.INVOICE_SEND,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.PAYMENT_DELETE,
    PERMISSIONS.PAYMENT_APPROVE,
    PERMISSIONS.DRAFT_PAYMENT_CREATE,
    PERMISSIONS.DRAFT_PAYMENT_READ,
    PERMISSIONS.DRAFT_PAYMENT_APPROVE,
    PERMISSIONS.DRAFT_PAYMENT_REJECT,
    PERMISSIONS.LATE_FEE_CREATE,
    PERMISSIONS.LATE_FEE_READ,
    PERMISSIONS.LATE_FEE_APPLY,
    PERMISSIONS.LATE_FEE_WAIVE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_MONITOR,
    PERMISSIONS.INTEGRATION_READ,
  ],

  finance_junior: [
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.DRAFT_PAYMENT_CREATE, // Can create draft payments
    PERMISSIONS.DRAFT_PAYMENT_READ, // Can view draft payments
    PERMISSIONS.LATE_FEE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.TRANSACTION_READ,
  ],

  operations_senior: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_CLIENT_APPROVE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_ACTIVATE,
    PERMISSIONS.MEMBER_DEACTIVATE,
    PERMISSIONS.MEMBER_ASSIGN_WORKSPACE,
    PERMISSIONS.MEMBER_MANAGE_ACCESS,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_APPROVE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_RESOLVE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_BLOCK,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.TRANSACTION_READ,
  ],

  operations_junior: [
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_MANAGE_ACCESS,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORT_READ,
  ],

  community_senior: [
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_ACTIVATE,
    PERMISSIONS.MEMBER_DEACTIVATE,
    PERMISSIONS.MEMBER_MANAGE_ACCESS,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.EVENT_PUBLISH,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_APPROVE,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_RESOLVE,
    PERMISSIONS.REPORT_READ,
  ],

  community_junior: [
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.EVENT_READ,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_READ,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.REPORT_READ,
  ],
};

// Helper to check if a permission grants access to an action
export const hasPermission = (userPermissions, requiredPermission) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }

  // Check for super admin permission
  if (userPermissions.includes(PERMISSIONS.SYSTEM_ADMIN)) {
    return true;
  }

  // Check for specific permission
  return userPermissions.includes(requiredPermission);
};

// Helper to check multiple permissions (user needs at least one)
export const hasAnyPermission = (userPermissions, requiredPermissions) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }

  // Check for super admin permission
  if (userPermissions.includes(PERMISSIONS.SYSTEM_ADMIN)) {
    return true;
  }

  // Check if user has any of the required permissions
  return requiredPermissions.some((permission) =>
    userPermissions.includes(permission)
  );
};

// Helper to check multiple permissions (user needs all)
export const hasAllPermissions = (userPermissions, requiredPermissions) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }

  // Check for super admin permission
  if (userPermissions.includes(PERMISSIONS.SYSTEM_ADMIN)) {
    return true;
  }

  // Check if user has all required permissions
  return requiredPermissions.every((permission) =>
    userPermissions.includes(permission)
  );
};
