import express from "express";
import authRoutes from "./auth.js";
import otpRoutes from "./otp.js";
import roleRoutes from "./roles.js";
import healthRoutes from "./health.js";
import clientRoutes from "./clients.js";
import contractRoutes from "./contracts.js";
import contractApprovalRoutes from "./contractApproval.js";
import contractCustomRoutes from "./contractCustom.js";
import invoiceRoutes from "./invoices.js";
import buildingsRoutes from "./buildings.js";
import buildingAmenitiesRoutes from "./buildingAmenities.js";
import cabinsRoutes from "./cabins.js";
import cabinAmenitiesRoutes from "./cabinAmenities.js";
import desksRoutes from "./desks.js";
import paymentsRoutes from "./payments.js";
import draftPaymentsRoutes from "./draftPayments.js";
import meetingRoomsRoutes from "./meetingRooms.js";
import meetingBookingsRoutes from "./meetingBookings.js";
import dayPassesRoutes from "./dayPasses.js";
import visitorsRoutes from "./visitors.js";
import ticketsRoutes from "./tickets.js";
import ticketCategoriesRoutes from "./ticketCategories.js";
import walletRoutes from "./wallet.js";
import memberRoutes from "./members.js";
import memberPortalRoutes from "./memberPortal.js";
import userRoutes from "./users.js";
import communityRoutes from "./community.js";
import tourRoutes from "./tourRoutes.js";
import webhookRoutes from "./webhooks.js";
import creditRoutes from "./credits.js";
import activityLogsRoutes from "./activityLogs.js";
import apiLogsRoutes from "./apiLogs.js";
import eventsRoutes from "./events.js";
import eventCategoriesRoutes from "./eventCategories.js";
import leadsRoutes from "./leads.js";
import notificationsRoutes from "./notifications.js";
import announcementsRoutes from "./announcements.js";
import accessRoutes from "./access.js";
import pincodeRoutes from "./pincode.js";
import matrixDevicesRoutes from "./matrixDevices.js";
import bhaifiRoutes from "./bhaifi.js";
import accessPointsRoutes from "./accessPoints.js";
import rfidCardsRoutes from "./rfidCards.js";
import accessEventsRoutes from "./accessEvents.js";
import provisioningJobsRoutes from "./provisioningJobs.js";
import matrixUsersRoutes from "./matrixUsers.js";
import memberIntegrationsRoutes from "./memberIntegrations.js";
import searchRoutes from "./search.js";
import securityDepositsRoutes from "./securityDeposits.js";
import documentEntitiesRoutes from "./documentEntities.js";
import dashboardRoutes from "./dashboard.js";
import meRoutes from "./me.js";
import zohoBooksRoutes from "./zohoBooks.js";
import locationsRoutes from "./locations.js";
import estimatesRoutes from "./estimates.js";
import partnerMyhqRoutes from "./partnerMyhq.js";
import notificationTemplatesRoutes from "./notificationTemplates.js";
import guestsRoutes from "./guests.js";
import commonAreasRoutes from "./commonAreas.js";
import templateDesignRoutes from "./templateDesigns.js";
import migrationRoutes from "./migration.js";
import cityRoutes from "./cityRoutes.js";
import privacyPolicyRoutes from "./privacyPolicyRoutes.js";
import notificationCategoriesRoutes from "./notificationCategories.js";
import discountBundleRoutes from "./discountBundles.js";
import docSupportRoutes from "./docSupportRoutes.js";
import printerRoutes from "./printer.js";
import appRequestsRoutes from "./appRequests.js";
import gstRoutes from "./gstRoutes.js";
import addOnsRoutes from "./addOns.js";

const router = express.Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/otp", otpRoutes);
router.use("/me", meRoutes);
router.use("/roles", roleRoutes);
router.use("/clients", clientRoutes);
router.use("/contracts", contractRoutes);
router.use("/contract-approvals", contractApprovalRoutes);
router.use("/contract-custom", contractCustomRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/buildings", buildingsRoutes);
router.use("/building-amenities", buildingAmenitiesRoutes);
router.use("/cabins", cabinsRoutes);
router.use("/cabin-amenities", cabinAmenitiesRoutes);
router.use("/desks", desksRoutes);
router.use("/payments", paymentsRoutes);
router.use("/draft-payments", draftPaymentsRoutes);
router.use("/meeting-rooms", meetingRoomsRoutes);
router.use("/meeting-bookings", meetingBookingsRoutes);
router.use("/day-passes", dayPassesRoutes);
router.use("/visitors", visitorsRoutes);
router.use("/tickets", ticketsRoutes);
router.use("/ticket-categories", ticketCategoriesRoutes);
router.use("/wallet", walletRoutes);
router.use("/members", memberRoutes);
router.use("/members/integrations", memberIntegrationsRoutes);
router.use("/member-portal", memberPortalRoutes);
router.use("/users", userRoutes);
router.use("/community", communityRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/credits", creditRoutes);
router.use("/activity-logs", activityLogsRoutes);
router.use("/api-logs", apiLogsRoutes);
router.use("/events", eventsRoutes);
router.use("/event-categories", eventCategoriesRoutes);
router.use("/leads", leadsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/notification-categories", notificationCategoriesRoutes);
router.use("/notification-templates", notificationTemplatesRoutes);
router.use("/guests", guestsRoutes);
router.use("/common-areas", commonAreasRoutes);
router.use("/template-designs", templateDesignRoutes);
router.use("/announcements", announcementsRoutes);
router.use("/pincode", pincodeRoutes);
router.use("/access", accessRoutes);
router.use("/access-points", accessPointsRoutes);
router.use("/rfid-cards", rfidCardsRoutes);
router.use("/access-events", accessEventsRoutes);
router.use("/provisioning-jobs", provisioningJobsRoutes);
router.use("/matrix-devices", matrixDevicesRoutes);
router.use("/bhaifi", bhaifiRoutes);
router.use("/matrix-users", matrixUsersRoutes);
router.use("/search", searchRoutes);
router.use("/security-deposits", securityDepositsRoutes);
router.use("/document-entities", documentEntitiesRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/zoho-books", zohoBooksRoutes);
router.use("/locations", locationsRoutes);
router.use("/proforma-invoices", estimatesRoutes);
router.use("/estimates", estimatesRoutes);
router.use("/partner/myhq", partnerMyhqRoutes);
router.use("/migration", migrationRoutes);
router.use("/cities", cityRoutes);
router.use("/tours", tourRoutes);
router.use("/privacy-policies", privacyPolicyRoutes);
router.use("/discount-bundles", discountBundleRoutes);
router.use("/doc-support", docSupportRoutes);
router.use("/printer", printerRoutes);
router.use("/app-requests", appRequestsRoutes);
router.use("/gst", gstRoutes);
router.use("/addons", addOnsRoutes);

export default router;
